###############
## 
####

# GPU: [0,1,2,3]
GPU: [1]
VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'StripeAwareNet'
# Optimization arguments.
OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 250
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  TRAIN_DIR: './rain100L/train'       # path to training data
  VAL_DIR: './rain100L/test' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  SAVE_IMAGES: True
  DIM: 256
  HEAD_DIM: 64
  BIAS: False

